*Cleaned .xls file manually to remove columns/rows not able to be parsed by pandas.*
*Also removed ailments clearly not caused by food like injuries, exposure to mechanical forces, natural disasters, other unintentional injuries, intentional injuries, self-harm, interpersonal violence, collective violence and legal intervention, drowning, falls, road injury, unintentional injuries, injuries, rabies, yellow fever, dengue and other vector diseases, SIDS, 
.*

In [64]:
import pandas as pd
import numpy as np
import matplotlib

disease_df = pd.read_excel("cleanedGHE2016_DALYs-2016-country.xlsx", encoding='latin-1')
columns = disease_df.iloc[:,0].tolist()
disease_df.tail()

,GHE cause,Afghanistan,Albania,Algeria,Angola,Antigua and Barbuda,Argentina,Armenia,Australia,Austria,...,United Republic of Tanzania,United States of America,Uruguay,Uzbekistan,Vanuatu,Venezuela (Bolivarian Republic of),Viet Nam,Yemen,Zambia,Zimbabwe
112,Dental caries,8.915272,0.786014,9.534396,4.450325,0.032470,16.825951,0.799637,4.550005,3.350795,...,12.178258,82.843689,1.386617,8.612052,0.075492,11.458681,18.545503,6.950519,3.593708,2.756622
113,Periodontal disease,13.291041,1.901364,26.689878,8.999782,0.101141,30.035238,1.901050,14.402867,9.295235,...,3.707525,142.809625,3.527374,13.416079,0.018951,23.685969,36.286257,11.120515,6.605976,1.594521
114,Edentulism,18.639215,6.205911,45.717420,13.403549,0.135974,58.413680,7.741004,64.388641,28.655879,...,14.810599,662.273879,5.601263,43.201856,0.117696,43.919465,48.381986,16.993919,4.523364,12.853295
115,Sudden infant death syndrome,38.220790,1.221607,24.417546,51.531099,0.008021,21.451418,0.267904,5.535792,0.669680,...,63.272940,131.566010,0.788645,8.043705,0.066019,1.465896,26.500207,56.060492,16.458028,3.868184
116,Poisonings,30.874814,0.817360,23.142287,59.014681,0.022178,15.040495,1.120259,4.354529,1.524359,...,115.454541,160.453618,0.752162,21.427973,0.142984,6.067724,42.517815,80.585481,38.797548,27.350160

In [44]:

del disease_df['GHE cause']
country_df = disease_df.transpose()
country_df.columns = columns
#country_df.sort_values('')
country_df.head(10)

,Population thousands,All Causes,Diarrhoeal diseases,Intestinal nematode infections,Ascariasis,Trichuriasis,Hookworm disease,Food-bourne trematodes,Otitis media,Maternal conditions,...,Gout,Neural tube defects,Cleft lip and cleft palate,Down syndrome,Congenital heart anomalies,Dental caries,Periodontal disease,Edentulism,Sudden infant death syndrome,Poisonings
Afghanistan,34656.0,18144.447543,709.743629,28.957996,27.998972,0.435021,0.524003,NaN,29.544030,225.251532,...,1.768880,93.810452,0.973907,12.664676,237.038007,8.915272,13.291041,18.639215,38.220790,30.874814
Albania,2926.0,883.875664,2.201231,0.001349,0.001349,NaN,NaN,NaN,1.090044,0.613733,...,0.404787,1.561217,0.017509,0.457162,9.831769,0.786014,1.901364,6.205911,1.221607,0.817360
Algeria,40606.0,10833.041172,154.800703,0.722583,0.590652,0.014567,0.117364,NaN,17.592817,61.974354,...,3.942043,27.865412,0.406976,24.578086,157.288703,9.534396,26.689878,45.717420,24.417546,23.142287
Angola,28813.0,16720.334678,1526.057294,25.657989,9.317757,1.401064,14.939168,NaN,16.938134,214.423040,...,1.414705,117.714277,5.441410,9.027421,211.273574,4.450325,8.999782,13.403549,51.531099,59.014681
Antigua and Barbuda,101.0,26.449705,0.142901,0.000334,0.000013,NaN,0.000321,NaN,0.034139,0.191435,...,0.008942,0.021694,0.004321,0.016165,0.414945,0.032470,0.101141,0.135974,0.008021,0.022178
Argentina,43847.0,12020.756742,36.303180,4.434276,0.647208,0.005259,3.781809,NaN,13.716664,29.051789,...,10.082325,24.934164,0.324358,14.553945,107.346439,16.825951,30.035238,58.413680,21.451418,15.040495
Armenia,2925.0,957.425877,3.147583,0.011540,0.001416,NaN,0.010124,NaN,1.218433,0.578987,...,0.432567,2.174530,0.052262,0.525686,6.757167,0.799637,1.901050,7.741004,0.267904,1.120259
Australia,24126.0,5580.727572,7.101818,NaN,NaN,NaN,NaN,NaN,4.920289,2.355278,...,8.755266,5.673717,0.185131,6.747238,17.269149,4.550005,14.402867,64.388641,5.535792,4.354529
Austria,8712.0,2402.566740,4.740230,NaN,NaN,NaN,NaN,NaN,2.444056,0.407466,...,3.195475,2.584441,0.064925,4.644185,5.903626,3.350795,9.295235,28.655879,0.669680,1.524359
Azerbaijan,9725.0,2892.854238,38.961588,0.067441,0.032029,NaN,0.035412,NaN,3.625077,3.147478,...,1.160892,5.979464,0.136026,1.986973,52.744917,2.528109,5.410238,18.370797,3.515664,3.910363

*Check one country*

In [45]:
United_States = country_df.loc[["United States of America"], :]
United_States.dropna()

United_States.sort_values(by='United States of America', axis=1, ascending=False)

,Population thousands,All Causes,Ischaemic heart disease,Chronic obstructive pulmonary disease,Diabetes mellitus,Alzheimer disease and other dementias,"Trachea, bronchus, lung cancers",Stroke,Opioid use disorders,Depressive disorders,...,Urolithiasis,Appendicitis,Acute glomerulonephritis,Cleft lip and cleft palate,Intestinal nematode infections,Ascariasis,Trichuriasis,Hookworm disease,Food-bourne trematodes,Vitamin A deficiency
United States of America,322180.0,100384.164781,9269.600899,4519.202379,4054.681575,3617.091421,3463.44572,3292.295255,2851.67451,2715.040493,...,25.210051,15.023549,2.802854,2.35842,NaN,NaN,NaN,NaN,NaN,NaN

*Find top N diseases for each country*


First I separated out the selected countries for which we have sufficient recipes, and then sorted them to get the top diseases. The first column is just the population data, which is necessary to include as it allows calculation of percent of population with each disease. For our purposes, it appears that the top 10 diseases allows for enough variety while not being overwhelming. But that number may change after further exploration or pattern mining.

*The Carribean is made up of 26 islands and sovereign nations, but not all are listed in the WHO database. For instance Puerto Rico is considered part of teh Carribean but is officially United States territory, so it is not listed alone on the WHO database*

In [46]:
#Caribbean Countries
Caribbean_countries = country_df.loc[["Cuba", "Haiti", "Dominican Republic", "Jamaica", "Trinidad and Tobago", "Bahamas", "Barbados", "Saint Lucia", "Saint Vincent and the Grenadines", "Grenada", "Antigua and Barbuda"]]

#need to sum each column and make it the column for combined dataframe for Carribean
Caribbean_countries.loc['Caribbean'] = pd.Series(Caribbean_countries.sum())
Caribbean_countries

Caribbean = Caribbean_countries.loc[["Caribbean"]].sort_values(by='Caribbean', axis=1, ascending=False)
Caribbean = Caribbean.iloc[:, : 20]

In [47]:
#China
China = country_df.loc[["China"]].sort_values(by='China', axis=1, ascending=False)
China = China.iloc[:, : 20]

In [48]:
#France
France = country_df.loc[["France"]].sort_values(by='France', axis=1, ascending=False)
France = France.iloc[:, : 20]

In [49]:
#Greece
Greece = country_df.loc[["Greece"]].sort_values(by='Greece', axis=1, ascending=False)
Greece = Greece.iloc[:, : 20]

In [50]:
#India
India = country_df.loc[["India"]].sort_values(by='India', axis=1, ascending=False)
India = India.iloc[:, : 20]

In [51]:
#Indonesia
Indonesia = country_df.loc[["Indonesia"]].sort_values(by='Indonesia', axis=1, ascending=False)
Indonesia = Indonesia.iloc[:, : 20]

In [52]:
#Ireland
Ireland = country_df.loc[["Ireland"]].sort_values(by='Ireland', axis=1, ascending=False)
Ireland = Ireland.iloc[:, : 20]

In [53]:
#Italy
Italy = country_df.loc[["Italy"]].sort_values(by='Italy', axis=1, ascending=False)
Italy = Italy.iloc[:, : 20]

In [54]:
#Japan
Japan = country_df.loc[["Japan"]].sort_values(by='Japan', axis=1, ascending=False)
Japan = Japan.iloc[:, : 20]

In [55]:
#Mexico
Mexico = country_df.loc[["Mexico"]].sort_values(by='Mexico', axis=1, ascending=False)
Mexico = Mexico.iloc[:, : 20]

In [56]:
#Philippines
Philippines = country_df.loc[["Philippines"]].sort_values(by='Philippines', axis=1, ascending=False)
Philippines = Philippines.iloc[:, : 20]

In [57]:
#Thailand
Thailand = country_df.loc[["Thailand"]].sort_values(by='Thailand', axis=1, ascending=False)
Thailand = Thailand.iloc[:, : 20]

In [58]:
#Viet Nam
Viet_Nam = country_df.loc[["Viet Nam"]].sort_values(by='Viet Nam', axis=1, ascending=False)
Viet_Nam = Viet_Nam.iloc[:, : 20]

In [59]:
#Russia
Russia = country_df.loc[["Russian Federation"]].sort_values(by='Russian Federation', axis=1, ascending=False)
Russia = Russia.iloc[:, : 20]

In [60]:
#South Korea
South_Korea = country_df.loc[["Republic of Korea"]].sort_values(by='Republic of Korea', axis=1, ascending=False)
South_Korea = South_Korea.iloc[:, : 20]

In [61]:
#UK
United_Kingdom = country_df.loc[["United Kingdom"]].sort_values(by='United Kingdom', axis=1, ascending=False)
United_Kingdom = United_Kingdom.iloc[:, : 20]

In [65]:
frames = [Caribbean, China, France, Greece, India, Indonesia, Ireland, Italy, Japan, Mexico, Philippines, Thailand, Viet_Nam, Russia, South_Korea, United_Kingdom]
combined_countries = pd.concat(frames, sort=True)
combined_countries
# note that NaN does not mean that the country does not have any instances of a particular disease, 
# but that the disease in question is not 
# in the top N diseases, in this case, top 20. 
# I will use this dataframe to attempt to cluster countries together based on similar diseases. 
# I may instead choose to take all diseases together to compare similarities across all diseases
# depending on how useful the results appear to be

,Alcohol use disorders,All Causes,Alzheimer disease and other dementias,Anxiety disorders,Asthma,Birth asphyxia and birth trauma,Brain and nervous system cancers,Breast cancer,"Cardiomyopathy, myocarditis, endocarditis",Chronic kidney disease due to diabetes,...,Pancreas cancer,Population thousands,Preterm birth complications,Prostate cancer,Schizophrenia,Skin diseases,Stomach cancer,Stroke,"Trachea, bronchus, lung cancers",Uncorrected refractive errors
Caribbean,NaN,13905.819584,156.013413,NaN,198.905045,290.911293,NaN,NaN,NaN,NaN,...,NaN,38390.0,477.236529,NaN,NaN,NaN,NaN,688.276747,195.919851,NaN
China,NaN,376370.900000,10041.762203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1411415.0,NaN,NaN,4561.340778,NaN,7759.098337,47588.808765,14705.861537,5583.694327
France,223.113543,16782.841238,677.400662,351.145909,193.112460,NaN,NaN,330.333607,NaN,NaN,...,225.665361,64721.0,NaN,NaN,NaN,NaN,NaN,594.916529,827.288245,NaN
Greece,NaN,3273.038198,69.024986,56.114990,NaN,NaN,34.471233,54.584690,NaN,NaN,...,38.295989,11184.0,NaN,NaN,NaN,NaN,32.137082,228.447943,167.675410,NaN
India,NaN,509005.725000,NaN,NaN,5504.450195,11832.813641,NaN,NaN,NaN,NaN,...,NaN,1324171.0,31005.755796,NaN,NaN,NaN,NaN,18800.954527,NaN,7221.915817
Indonesia,NaN,87574.365188,1045.337914,NaN,1680.670286,1582.689706,NaN,NaN,NaN,NaN,...,NaN,261115.0,2574.502710,NaN,NaN,947.452089,NaN,6777.595875,940.143704,1093.891718
Ireland,13.790877,1070.385310,35.414323,24.458824,18.303144,NaN,NaN,21.155839,NaN,NaN,...,NaN,4726.0,NaN,NaN,NaN,12.755075,NaN,34.606225,41.684412,NaN
Italy,NaN,17125.665680,666.743901,316.509992,NaN,NaN,NaN,317.549798,NaN,NaN,...,223.835288,59430.0,NaN,NaN,NaN,NaN,202.813075,860.755109,698.588108,205.276397
Japan,NaN,35619.331059,1126.773893,415.865717,NaN,NaN,NaN,NaN,NaN,NaN,...,614.418695,127749.0,NaN,NaN,NaN,NaN,950.289384,2198.029351,1389.004544,618.590074
Mexico,396.771078,31199.489906,NaN,366.859752,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,127540.0,713.022176,NaN,NaN,391.296531,NaN,791.315846,NaN,522.911660
Philippines,NaN,33904.976344,NaN,NaN,695.288042,714.234021,NaN,NaN,NaN,443.678553,...,NaN,103320.0,1127.774078,NaN,NaN,438.014289,NaN,2509.767846,NaN,505.099163
Thailand,NaN,22137.704125,632.243630,249.346168,258.959020,NaN,NaN,NaN,NaN,444.196024,...,NaN,68864.0,283.621127,NaN,NaN,323.829316,NaN,1184.202454,528.034045,NaN
Viet Nam,NaN,25192.804109,504.198614,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,94569.0,834.190955,NaN,NaN,324.340962,368.283732,1923.113311,593.818776,334.685819
Russian Federation,2060.365566,64873.714094,818.699202,NaN,NaN,NaN,NaN,830.939828,1969.615125,NaN,...,NaN,143965.0,NaN,NaN,NaN,NaN,1024.450448,6226.391860,1678.847647,770.013873
Republic of Korea,166.184640,11312.673324,272.677699,197.404469,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,50792.0,NaN,NaN,NaN,NaN,239.635116,620.519748,407.103899,189.846986
United Kingdom,NaN,17925.027078,997.214261,296.785430,251.479227,NaN,NaN,311.613912,NaN,NaN,...,NaN,65789.0,NaN,205.507977,NaN,211.588610,NaN,684.912578,741.426064,NaN