*Cleaned .xls file manually to remove columns/rows not able to be parsed by pandas.*
*Also removed ailments clearly not caused by food like injuries, exposure to mechanical forces, natural disasters, other unintentional injuries, intentional injuries, self-harm, interpersonal violence, collective violence and legal intervention, drowning, falls, road injury, unintentional injuries, injuries, rabies, yellow fever, dengue and other vector diseases, SIDS, 
.*

In [20]:
import pandas as pd
import numpy as np

disease_df = pd.read_excel("cleanedGHE2016_DALYs-2016-country.xlsx", encoding='latin-1')
columns = disease_df.iloc[:,0].tolist()
disease_df.tail()

,GHE cause,Afghanistan,Albania,Algeria,Angola,Antigua and Barbuda,Argentina,Armenia,Australia,Austria,...,United Republic of Tanzania,United States of America,Uruguay,Uzbekistan,Vanuatu,Venezuela (Bolivarian Republic of),Viet Nam,Yemen,Zambia,Zimbabwe
112,Dental caries,8.915272,0.786014,9.534396,4.450325,0.032470,16.825951,0.799637,4.550005,3.350795,...,12.178258,82.843689,1.386617,8.612052,0.075492,11.458681,18.545503,6.950519,3.593708,2.756622
113,Periodontal disease,13.291041,1.901364,26.689878,8.999782,0.101141,30.035238,1.901050,14.402867,9.295235,...,3.707525,142.809625,3.527374,13.416079,0.018951,23.685969,36.286257,11.120515,6.605976,1.594521
114,Edentulism,18.639215,6.205911,45.717420,13.403549,0.135974,58.413680,7.741004,64.388641,28.655879,...,14.810599,662.273879,5.601263,43.201856,0.117696,43.919465,48.381986,16.993919,4.523364,12.853295
115,Sudden infant death syndrome,38.220790,1.221607,24.417546,51.531099,0.008021,21.451418,0.267904,5.535792,0.669680,...,63.272940,131.566010,0.788645,8.043705,0.066019,1.465896,26.500207,56.060492,16.458028,3.868184
116,Poisonings,30.874814,0.817360,23.142287,59.014681,0.022178,15.040495,1.120259,4.354529,1.524359,...,115.454541,160.453618,0.752162,21.427973,0.142984,6.067724,42.517815,80.585481,38.797548,27.350160

In [21]:

del disease_df['GHE cause']
country_df = disease_df.transpose()
country_df.columns = columns
#country_df.sort_values('')
country_df.head(10)

,Population thousands,All Causes,Diarrhoeal diseases,Intestinal nematode infections,Ascariasis,Trichuriasis,Hookworm disease,Food-bourne trematodes,Otitis media,Maternal conditions,...,Gout,Neural tube defects,Cleft lip and cleft palate,Down syndrome,Congenital heart anomalies,Dental caries,Periodontal disease,Edentulism,Sudden infant death syndrome,Poisonings
Afghanistan,34656.0,18144.447543,709.743629,28.957996,27.998972,0.435021,0.524003,NaN,29.544030,225.251532,...,1.768880,93.810452,0.973907,12.664676,237.038007,8.915272,13.291041,18.639215,38.220790,30.874814
Albania,2926.0,883.875664,2.201231,0.001349,0.001349,NaN,NaN,NaN,1.090044,0.613733,...,0.404787,1.561217,0.017509,0.457162,9.831769,0.786014,1.901364,6.205911,1.221607,0.817360
Algeria,40606.0,10833.041172,154.800703,0.722583,0.590652,0.014567,0.117364,NaN,17.592817,61.974354,...,3.942043,27.865412,0.406976,24.578086,157.288703,9.534396,26.689878,45.717420,24.417546,23.142287
Angola,28813.0,16720.334678,1526.057294,25.657989,9.317757,1.401064,14.939168,NaN,16.938134,214.423040,...,1.414705,117.714277,5.441410,9.027421,211.273574,4.450325,8.999782,13.403549,51.531099,59.014681
Antigua and Barbuda,101.0,26.449705,0.142901,0.000334,0.000013,NaN,0.000321,NaN,0.034139,0.191435,...,0.008942,0.021694,0.004321,0.016165,0.414945,0.032470,0.101141,0.135974,0.008021,0.022178
Argentina,43847.0,12020.756742,36.303180,4.434276,0.647208,0.005259,3.781809,NaN,13.716664,29.051789,...,10.082325,24.934164,0.324358,14.553945,107.346439,16.825951,30.035238,58.413680,21.451418,15.040495
Armenia,2925.0,957.425877,3.147583,0.011540,0.001416,NaN,0.010124,NaN,1.218433,0.578987,...,0.432567,2.174530,0.052262,0.525686,6.757167,0.799637,1.901050,7.741004,0.267904,1.120259
Australia,24126.0,5580.727572,7.101818,NaN,NaN,NaN,NaN,NaN,4.920289,2.355278,...,8.755266,5.673717,0.185131,6.747238,17.269149,4.550005,14.402867,64.388641,5.535792,4.354529
Austria,8712.0,2402.566740,4.740230,NaN,NaN,NaN,NaN,NaN,2.444056,0.407466,...,3.195475,2.584441,0.064925,4.644185,5.903626,3.350795,9.295235,28.655879,0.669680,1.524359
Azerbaijan,9725.0,2892.854238,38.961588,0.067441,0.032029,NaN,0.035412,NaN,3.625077,3.147478,...,1.160892,5.979464,0.136026,1.986973,52.744917,2.528109,5.410238,18.370797,3.515664,3.910363

*Check one country*

In [22]:
United_States = country_df.loc[["United States of America"], :]
United_States.dropna()

United_States.sort_values(by='United States of America', axis=1, ascending=False)

,Population thousands,All Causes,Ischaemic heart disease,Chronic obstructive pulmonary disease,Diabetes mellitus,Alzheimer disease and other dementias,"Trachea, bronchus, lung cancers",Stroke,Opioid use disorders,Depressive disorders,...,Urolithiasis,Appendicitis,Acute glomerulonephritis,Cleft lip and cleft palate,Intestinal nematode infections,Ascariasis,Trichuriasis,Hookworm disease,Food-bourne trematodes,Vitamin A deficiency
United States of America,322180.0,100384.164781,9269.600899,4519.202379,4054.681575,3617.091421,3463.44572,3292.295255,2851.67451,2715.040493,...,25.210051,15.023549,2.802854,2.35842,NaN,NaN,NaN,NaN,NaN,NaN

*Find top N diseases for each country*


First I separated out the selected countries for which we have sufficient recipes, and then sorted them to get the top diseases. The first column is just the population data, which is necessary to include as it allows calculation of percent of population with each disease. For our purposes, it appears that the top 10 diseases allows for enough variety while not being overwhelming. But that number may change after further exploration or pattern mining.

*The Carribean is made up of 26 islands and sovereign nations, but not all are listed in the WHO database. For instance Puerto Rico is considered part of teh Carribean but is officially United States territory, so it is not listed alone on the WHO database*

In [23]:
#Caribbean Countries
Caribbean_countries = country_df.loc[["Cuba", "Haiti", "Dominican Republic", "Jamaica", "Trinidad and Tobago", "Bahamas", "Barbados", "Saint Lucia", "Saint Vincent and the Grenadines", "Grenada", "Antigua and Barbuda"]]

#need to sum each column and make it the column for combined dataframe for Carribean
Caribbean_countries.loc['Caribbean'] = pd.Series(Caribbean_countries.sum())
Caribbean_countries

Caribbean = Caribbean_countries.loc[["Caribbean"]].sort_values(by='Caribbean', axis=1, ascending=False)
Caribbean

,Population thousands,All Causes,Ischaemic heart disease,Stroke,Diabetes mellitus,Preterm birth complications,Haemorrhagic stroke,Diarrhoeal diseases,Nutritional deficiencies,Birth asphyxia and birth trauma,...,Thalassaemias,Testicular cancer,Urolithiasis,Vitamin A deficiency,Mesothelioma,Amphetamine use disorders,Cleft lip and cleft palate,Trichuriasis,Acute glomerulonephritis,Food-bourne trematodes
Caribbean,38390.0,13905.819584,1130.664218,688.276747,516.697315,477.236529,401.140098,332.259223,309.592169,290.911293,...,2.651187,1.963121,1.63053,1.577213,1.019587,0.833663,0.657269,0.554451,0.365329,0.0

In [24]:
#China
China = country_df.loc[["China"]].sort_values(by='China', axis=1, ascending=False)

China.drop([])

,Population thousands,All Causes,Stroke,Ischaemic heart disease,Haemorrhagic stroke,Ischaemic stroke,Chronic obstructive pulmonary disease,"Trachea, bronchus, lung cancers",Liver cancer,Alzheimer disease and other dementias,...,Multiple sclerosis,Sudden infant death syndrome,Down syndrome,Ascariasis,Cleft lip and cleft palate,Hodgkin lymphoma,Testicular cancer,Vitamin A deficiency,Trichuriasis,Sickle cell disorders and trait
China,1411415.0,376370.9,47588.808765,37324.428987,27271.836983,20316.971024,17937.916706,14705.861537,12207.951753,10041.762203,...,73.68462,70.900173,69.330003,44.019045,42.150419,37.839745,35.996814,25.269238,12.112664,8.759536

In [25]:
#France
France = country_df.loc[["France"]].sort_values(by='France', axis=1, ascending=False)
France

,Population thousands,All Causes,Ischaemic heart disease,"Trachea, bronchus, lung cancers",Alzheimer disease and other dementias,Stroke,Depressive disorders,Major depressive disorder,Colon and rectum cancers,Diabetes mellitus,...,Urolithiasis,Appendicitis,Cleft lip and cleft palate,Acute glomerulonephritis,Intestinal nematode infections,Ascariasis,Trichuriasis,Hookworm disease,Food-bourne trematodes,Vitamin A deficiency
France,64721.0,16782.841238,927.52799,827.288245,677.400662,594.916529,517.92027,424.747749,379.553159,379.072344,...,3.199201,2.319471,0.341218,0.208776,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
#Greece
Greece = country_df.loc[["Greece"]].sort_values(by='Greece', axis=1, ascending=False)
Greece

,Population thousands,All Causes,Ischaemic heart disease,Stroke,"Trachea, bronchus, lung cancers",Chronic obstructive pulmonary disease,Ischaemic stroke,Haemorrhagic stroke,Depressive disorders,Alzheimer disease and other dementias,...,Amphetamine use disorders,Appendicitis,Cleft lip and cleft palate,Acute glomerulonephritis,Intestinal nematode infections,Ascariasis,Trichuriasis,Hookworm disease,Food-bourne trematodes,Vitamin A deficiency
Greece,11184.0,3273.038198,373.901907,228.447943,167.67541,120.427489,119.817539,108.630405,85.859433,69.024986,...,0.238987,0.227906,0.073083,0.038947,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
#India
India = country_df.loc[["India"]].sort_values(by='India', axis=1, ascending=False)
India

,Population thousands,All Causes,Ischaemic heart disease,Preterm birth complications,Chronic obstructive pulmonary disease,Nutritional deficiencies,Diarrhoeal diseases,Stroke,Iron-deficiency anaemia,Birth asphyxia and birth trauma,...,Cocaine use disorders,Testicular cancer,Attention deficit/hyperactivity syndrome,Malignant skin melanoma,Cleft lip and cleft palate,Acute glomerulonephritis,Amphetamine use disorders,Trichuriasis,Mesothelioma,Food-bourne trematodes
India,1324171.0,509005.725,44282.756687,31005.755796,22927.959119,22621.557953,19732.522547,18800.954527,16271.593207,11832.813641,...,69.088475,65.396187,58.226222,52.915571,47.133395,42.298621,30.556722,29.358873,17.668985,NaN

In [28]:
#Indonesia
Indonesia = country_df.loc[["Indonesia"]].sort_values(by='Indonesia', axis=1, ascending=False)
Indonesia

,Population thousands,All Causes,Ischaemic heart disease,Stroke,Haemorrhagic stroke,Diabetes mellitus,Preterm birth complications,Diarrhoeal diseases,Chronic obstructive pulmonary disease,Ischaemic stroke,...,Urolithiasis,Multiple sclerosis,Trichuriasis,Cocaine use disorders,Vitamin A deficiency,Mesothelioma,Cleft lip and cleft palate,Sickle cell disorders and trait,Acute glomerulonephritis,Food-bourne trematodes
Indonesia,261115.0,87574.365188,8487.848569,6777.595875,4779.366857,4033.045144,2574.50271,2295.870563,2000.106363,1998.229134,...,12.496956,10.388922,9.246829,7.179485,7.110394,4.268868,4.101145,3.398187,2.545504,NaN

In [29]:
#Ireland
Ireland = country_df.loc[["Ireland"]].sort_values(by='Ireland', axis=1, ascending=False)
Ireland

,Population thousands,All Causes,Ischaemic heart disease,"Trachea, bronchus, lung cancers",Chronic obstructive pulmonary disease,Alzheimer disease and other dementias,Stroke,Depressive disorders,Major depressive disorder,Migraine,...,Appendicitis,Sickle cell disorders and trait,Acute glomerulonephritis,Cleft lip and cleft palate,Intestinal nematode infections,Ascariasis,Trichuriasis,Hookworm disease,Food-bourne trematodes,Vitamin A deficiency
Ireland,4726.0,1070.38531,85.725415,41.684412,35.934094,35.414323,34.606225,33.395762,25.944533,24.474758,...,0.17985,0.138976,0.0325,0.028559,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
#Italy
Italy = country_df.loc[["Italy"]].sort_values(by='Italy', axis=1, ascending=False)
Italy

,Population thousands,All Causes,Ischaemic heart disease,Stroke,"Trachea, bronchus, lung cancers",Alzheimer disease and other dementias,Diabetes mellitus,Chronic obstructive pulmonary disease,Ischaemic stroke,Haemorrhagic stroke,...,Appendicitis,Cleft lip and cleft palate,Acute glomerulonephritis,Sickle cell disorders and trait,Intestinal nematode infections,Ascariasis,Trichuriasis,Hookworm disease,Food-bourne trematodes,Vitamin A deficiency
Italy,59430.0,17125.66568,1537.538067,860.755109,698.588108,666.743901,579.102149,452.232585,442.253391,418.501717,...,1.245931,0.281267,0.224009,0.213331,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
#Japan
Japan = country_df.loc[["Japan"]].sort_values(by='Japan', axis=1, ascending=False)
Japan

,Population thousands,All Causes,Ischaemic heart disease,Stroke,"Trachea, bronchus, lung cancers",Ischaemic stroke,Alzheimer disease and other dementias,Chronic obstructive pulmonary disease,Colon and rectum cancers,Diabetes mellitus,...,Testicular cancer,Sickle cell disorders and trait,Acute glomerulonephritis,Cleft lip and cleft palate,Food-bourne trematodes,Intestinal nematode infections,Ascariasis,Trichuriasis,Hookworm disease,Vitamin A deficiency
Japan,127749.0,35619.331059,2315.051,2198.029351,1389.004544,1234.380297,1126.773893,1068.790269,1015.668498,1004.445687,...,4.279555,2.609226,1.537705,1.179778,0.709912,0.709912,NaN,NaN,NaN,NaN

In [32]:
#Mexico
Mexico = country_df.loc[["Mexico"]].sort_values(by='Mexico', axis=1, ascending=False)
Mexico

,Population thousands,All Causes,Diabetes mellitus,Ischaemic heart disease,Stroke,Preterm birth complications,Depressive disorders,Migraine,Chronic obstructive pulmonary disease,Uncorrected refractive errors,...,Amphetamine use disorders,Attention deficit/hyperactivity syndrome,Mesothelioma,Cleft lip and cleft palate,Vitamin A deficiency,Cannabis use disorders,Nasopharynx,Acute glomerulonephritis,Hookworm disease,Food-bourne trematodes
Mexico,127540.0,31199.489906,3507.629066,2074.962176,791.315846,713.022176,606.051403,536.244586,523.402553,522.91166,...,9.063081,9.049653,8.383424,6.021894,4.965752,4.871342,3.199603,1.461602,0.172956,NaN

In [33]:
#Philippines
Philippines = country_df.loc[["Philippines"]].sort_values(by='Philippines', axis=1, ascending=False)
Philippines

,Population thousands,All Causes,Ischaemic heart disease,Stroke,Haemorrhagic stroke,Diabetes mellitus,Preterm birth complications,Chronic obstructive pulmonary disease,Birth asphyxia and birth trauma,Asthma,...,Hodgkin lymphoma,Testicular cancer,Inflammatory bowel disease,Malignant skin melanoma,Cocaine use disorders,Vitamin A deficiency,Multiple sclerosis,Food-bourne trematodes,Sickle cell disorders and trait,Mesothelioma
Philippines,103320.0,33904.976344,3374.754556,2509.767846,1955.113522,1200.171601,1127.774078,861.155083,714.234021,695.288042,...,5.024854,4.628358,4.159877,3.892708,2.796294,2.272066,2.186763,1.692957,1.356243,0.420603

In [34]:
#Thailand
Thailand = country_df.loc[["Thailand"]].sort_values(by='Thailand', axis=1, ascending=False)
Thailand

,Population thousands,All Causes,Ischaemic heart disease,Stroke,Haemorrhagic stroke,Diabetes mellitus,Chronic obstructive pulmonary disease,Liver cancer,Alzheimer disease and other dementias,"Trachea, bronchus, lung cancers",...,Multiple sclerosis,Testicular cancer,Cocaine use disorders,Ascariasis,Mesothelioma,Vitamin A deficiency,Acute glomerulonephritis,Cleft lip and cleft palate,Sickle cell disorders and trait,Trichuriasis
Thailand,68864.0,22137.704125,1321.498835,1184.202454,814.081239,789.061113,773.556792,674.481855,632.24363,528.034045,...,3.711375,3.614694,2.062733,1.046411,0.855627,0.577818,0.521563,0.456194,0.227413,0.095528

In [35]:
#Viet Nam
Viet_Nam = country_df.loc[["Viet Nam"]].sort_values(by='Viet Nam', axis=1, ascending=False)
Viet_Nam

,Population thousands,All Causes,Stroke,Ischaemic heart disease,Haemorrhagic stroke,Liver cancer,Preterm birth complications,Diabetes mellitus,Chronic obstructive pulmonary disease,Ischaemic stroke,...,Multiple sclerosis,Cocaine use disorders,Gallbladder and biliary tract cancer,Malignant skin melanoma,Urolithiasis,Cleft lip and cleft palate,Testicular cancer,Vitamin A deficiency,Acute glomerulonephritis,Sickle cell disorders and trait
Viet Nam,94569.0,25192.804109,1923.113311,1310.044142,1278.916777,945.8851,834.190955,736.4493,677.673431,644.196545,...,3.980493,3.93322,2.897447,2.877759,2.419026,1.690937,1.326474,1.051543,0.720423,0.682266

In [36]:
#Russia
Russia = country_df.loc[["Russian Federation"]].sort_values(by='Russian Federation', axis=1, ascending=False)
Russia

,Population thousands,All Causes,Ischaemic heart disease,Stroke,Ischaemic stroke,Alcohol use disorders,"Cardiomyopathy, myocarditis, endocarditis",Haemorrhagic stroke,"Trachea, bronchus, lung cancers",Colon and rectum cancers,...,Attention deficit/hyperactivity syndrome,Sickle cell disorders and trait,Acute glomerulonephritis,Food-bourne trematodes,Intestinal nematode infections,Cleft lip and cleft palate,Ascariasis,Trichuriasis,Hookworm disease,Vitamin A deficiency
Russian Federation,143965.0,64873.714094,11111.42047,6226.39186,4410.773014,2060.365566,1969.615125,1815.61881,1678.847647,1140.206738,...,10.817469,9.946873,5.112576,1.650506,1.650506,1.183711,NaN,NaN,NaN,NaN

In [37]:
#South Korea
South_Korea = country_df.loc[["Republic of Korea"]].sort_values(by='Republic of Korea', axis=1, ascending=False)
South_Korea

,Population thousands,All Causes,Stroke,Diabetes mellitus,Ischaemic heart disease,"Trachea, bronchus, lung cancers",Depressive disorders,Ischaemic stroke,Liver cancer,Major depressive disorder,...,Attention deficit/hyperactivity syndrome,Hodgkin lymphoma,Appendicitis,Testicular cancer,Acute glomerulonephritis,Cleft lip and cleft palate,Hookworm disease,Trichuriasis,Ascariasis,Vitamin A deficiency
Republic of Korea,50792.0,11312.673324,620.519748,512.283235,492.953599,407.103899,379.924579,343.521827,327.551915,322.346566,...,2.615585,2.176001,1.838911,0.946418,0.347948,0.264054,0.187981,0.000001,NaN,NaN

In [38]:
#UK
United_Kingdom = country_df.loc[["United Kingdom"]].sort_values(by='United Kingdom', axis=1, ascending=False)
United_Kingdom

,Population thousands,All Causes,Ischaemic heart disease,Alzheimer disease and other dementias,"Trachea, bronchus, lung cancers",Stroke,Chronic obstructive pulmonary disease,Depressive disorders,Major depressive disorder,Colon and rectum cancers,...,Appendicitis,Sickle cell disorders and trait,Acute glomerulonephritis,Cleft lip and cleft palate,Ascariasis,Intestinal nematode infections,Trichuriasis,Hookworm disease,Food-bourne trematodes,Vitamin A deficiency
United Kingdom,65789.0,17925.027078,1335.34633,997.214261,741.426064,684.912578,680.107245,481.363761,373.846726,363.828503,...,2.891796,2.735728,0.436859,0.397856,0.001245,0.001245,NaN,NaN,NaN,NaN