*Cleaned .xls file manually to remove columns/rows not able to be parsed by pandas.*
*Also removed ailments clearly not caused by food like injuries, exposure to mechanical forces, natural disasters, other unintentional injuries, intentional injuries, self-harm, interpersonal violence, collective violence and legal intervention, drowning, falls, road injury, unintentional injuries, injuries, rabies, yellow fever, dengue and other vector diseases, SIDS, 
.*

In [83]:
import pandas as pd
import numpy as np
import matplotlib

disease_df = pd.read_excel("cleanedGHE2016_DALYs-2016-country.xlsx", encoding='latin-1')
columns = disease_df.iloc[:,0].tolist()
disease_df.tail()

,GHE cause,Afghanistan,Albania,Algeria,Angola,Antigua and Barbuda,Argentina,Armenia,Australia,Austria,...,United Republic of Tanzania,United States of America,Uruguay,Uzbekistan,Vanuatu,Venezuela (Bolivarian Republic of),Viet Nam,Yemen,Zambia,Zimbabwe
107,Dental caries,8.915272,0.786014,9.534396,4.450325,0.032470,16.825951,0.799637,4.550005,3.350795,...,12.178258,82.843689,1.386617,8.612052,0.075492,11.458681,18.545503,6.950519,3.593708,2.756622
108,Periodontal disease,13.291041,1.901364,26.689878,8.999782,0.101141,30.035238,1.901050,14.402867,9.295235,...,3.707525,142.809625,3.527374,13.416079,0.018951,23.685969,36.286257,11.120515,6.605976,1.594521
109,Edentulism,18.639215,6.205911,45.717420,13.403549,0.135974,58.413680,7.741004,64.388641,28.655879,...,14.810599,662.273879,5.601263,43.201856,0.117696,43.919465,48.381986,16.993919,4.523364,12.853295
110,Sudden infant death syndrome,38.220790,1.221607,24.417546,51.531099,0.008021,21.451418,0.267904,5.535792,0.669680,...,63.272940,131.566010,0.788645,8.043705,0.066019,1.465896,26.500207,56.060492,16.458028,3.868184
111,Poisonings,30.874814,0.817360,23.142287,59.014681,0.022178,15.040495,1.120259,4.354529,1.524359,...,115.454541,160.453618,0.752162,21.427973,0.142984,6.067724,42.517815,80.585481,38.797548,27.350160

In [84]:

del disease_df['GHE cause']
country_df = disease_df.transpose()
country_df.columns = columns
#country_df.sort_values('')
country_df.head(10)

,Population thousands,All Causes,Diarrhoeal diseases,Intestinal nematode infections,Ascariasis,Trichuriasis,Hookworm disease,Food-bourne trematodes,Otitis media,Maternal conditions,...,Gout,Neural tube defects,Cleft lip and cleft palate,Down syndrome,Congenital heart anomalies,Dental caries,Periodontal disease,Edentulism,Sudden infant death syndrome,Poisonings
Afghanistan,34656.0,18144.447543,709.743629,28.957996,27.998972,0.435021,0.524003,NaN,29.544030,225.251532,...,1.768880,93.810452,0.973907,12.664676,237.038007,8.915272,13.291041,18.639215,38.220790,30.874814
Albania,2926.0,883.875664,2.201231,0.001349,0.001349,NaN,NaN,NaN,1.090044,0.613733,...,0.404787,1.561217,0.017509,0.457162,9.831769,0.786014,1.901364,6.205911,1.221607,0.817360
Algeria,40606.0,10833.041172,154.800703,0.722583,0.590652,0.014567,0.117364,NaN,17.592817,61.974354,...,3.942043,27.865412,0.406976,24.578086,157.288703,9.534396,26.689878,45.717420,24.417546,23.142287
Angola,28813.0,16720.334678,1526.057294,25.657989,9.317757,1.401064,14.939168,NaN,16.938134,214.423040,...,1.414705,117.714277,5.441410,9.027421,211.273574,4.450325,8.999782,13.403549,51.531099,59.014681
Antigua and Barbuda,101.0,26.449705,0.142901,0.000334,0.000013,NaN,0.000321,NaN,0.034139,0.191435,...,0.008942,0.021694,0.004321,0.016165,0.414945,0.032470,0.101141,0.135974,0.008021,0.022178
Argentina,43847.0,12020.756742,36.303180,4.434276,0.647208,0.005259,3.781809,NaN,13.716664,29.051789,...,10.082325,24.934164,0.324358,14.553945,107.346439,16.825951,30.035238,58.413680,21.451418,15.040495
Armenia,2925.0,957.425877,3.147583,0.011540,0.001416,NaN,0.010124,NaN,1.218433,0.578987,...,0.432567,2.174530,0.052262,0.525686,6.757167,0.799637,1.901050,7.741004,0.267904,1.120259
Australia,24126.0,5580.727572,7.101818,NaN,NaN,NaN,NaN,NaN,4.920289,2.355278,...,8.755266,5.673717,0.185131,6.747238,17.269149,4.550005,14.402867,64.388641,5.535792,4.354529
Austria,8712.0,2402.566740,4.740230,NaN,NaN,NaN,NaN,NaN,2.444056,0.407466,...,3.195475,2.584441,0.064925,4.644185,5.903626,3.350795,9.295235,28.655879,0.669680,1.524359
Azerbaijan,9725.0,2892.854238,38.961588,0.067441,0.032029,NaN,0.035412,NaN,3.625077,3.147478,...,1.160892,5.979464,0.136026,1.986973,52.744917,2.528109,5.410238,18.370797,3.515664,3.910363

*Check one country*

In [85]:
United_States = country_df.loc[["United States of America"], :]
United_States.dropna()

United_States.sort_values(by='United States of America', axis=1, ascending=False)

,Population thousands,All Causes,Ischaemic heart disease,Chronic obstructive pulmonary disease,Diabetes mellitus,Alzheimer disease and other dementias,"Trachea, bronchus, lung cancers",Opioid use disorders,Depressive disorders,Major depressive disorder,...,Urolithiasis,Appendicitis,Acute glomerulonephritis,Cleft lip and cleft palate,Intestinal nematode infections,Ascariasis,Trichuriasis,Hookworm disease,Food-bourne trematodes,Vitamin A deficiency
United States of America,322180.0,100384.164781,9269.600899,4519.202379,4054.681575,3617.091421,3463.44572,2851.67451,2715.040493,2192.994249,...,25.210051,15.023549,2.802854,2.35842,NaN,NaN,NaN,NaN,NaN,NaN

*Find top N diseases for each country*


First I separated out the selected countries for which we have sufficient recipes, and then sorted them to get the top diseases. The first column is just the population data, which is necessary to include as it allows calculation of percent of population with each disease. For our purposes, it appears that the top 10 diseases allows for enough variety while not being overwhelming. But that number may change after further exploration or pattern mining.

*The Carribean is made up of 26 islands and sovereign nations, but not all are listed in the WHO database. For instance Puerto Rico is considered part of teh Carribean but is officially United States territory, so it is not listed alone on the WHO database*

In [86]:
#Caribbean Countries
Caribbean_countries = country_df.loc[["Cuba", "Haiti", "Dominican Republic", "Jamaica", "Trinidad and Tobago", "Bahamas", "Barbados", "Saint Lucia", "Saint Vincent and the Grenadines", "Grenada", "Antigua and Barbuda"]]

#need to sum each column and make it the column for combined dataframe for Carribean
Caribbean_countries.loc['Caribbean'] = pd.Series(Caribbean_countries.sum())
Caribbean_countries

Caribbean = Caribbean_countries.loc[["Caribbean"]].sort_values(by='Caribbean', axis=1, ascending=False)
Caribbean = Caribbean.iloc[:, : 20]
Caribbean

,Population thousands,All Causes,Ischaemic heart disease,Diabetes mellitus,Preterm birth complications,Haemorrhagic stroke,Diarrhoeal diseases,Nutritional deficiencies,Ischaemic stroke,Depressive disorders,Asthma,Major depressive disorder,"Trachea, bronchus, lung cancers",Chronic obstructive pulmonary disease,Iron-deficiency anaemia,Migraine,Alzheimer disease and other dementias,Anxiety disorders,Congenital heart anomalies,Hypertensive heart disease
Caribbean,38390.0,13905.819584,1130.664218,516.697315,477.236529,401.140098,332.259223,309.592169,287.136649,236.557405,198.905045,197.854976,195.919851,193.08467,183.720418,163.313653,156.013413,152.777611,152.367031,138.649998

In [87]:
#China
China = country_df.loc[["China"]].sort_values(by='China', axis=1, ascending=False)
China = China.iloc[:, : 20]
China

,Population thousands,All Causes,Ischaemic heart disease,Haemorrhagic stroke,Ischaemic stroke,Chronic obstructive pulmonary disease,"Trachea, bronchus, lung cancers",Liver cancer,Alzheimer disease and other dementias,Diabetes mellitus,Depressive disorders,Stomach cancer,Liver cancer secondary to hepatitis B,Major depressive disorder,Hypertensive heart disease,Oesophagus cancer,Schizophrenia,Osteoarthritis,Anxiety disorders,Migraine
China,1411415.0,376370.9,37324.428987,27271.836983,20316.971024,17937.916706,14705.861537,12207.951753,10041.762203,9289.399875,8627.776035,7759.098337,7153.218631,5967.554017,5208.659807,4728.133102,4561.340778,4323.652582,4275.02473,3838.527054

In [88]:
#France
France = country_df.loc[["France"]].sort_values(by='France', axis=1, ascending=False)
France = France.iloc[:, : 20]
France

,Population thousands,All Causes,Ischaemic heart disease,"Trachea, bronchus, lung cancers",Alzheimer disease and other dementias,Depressive disorders,Major depressive disorder,Colon and rectum cancers,Diabetes mellitus,Anxiety disorders,Migraine,Breast cancer,Ischaemic stroke,Chronic obstructive pulmonary disease,Haemorrhagic stroke,Pancreas cancer,Alcohol use disorders,Liver cancer,Asthma,Skin diseases
France,64721.0,16782.841238,927.52799,827.288245,677.400662,517.92027,424.747749,379.553159,379.072344,351.145909,334.592316,330.333607,320.022922,287.340769,274.893606,225.665361,223.113543,194.099785,193.11246,189.569308

In [89]:
#Greece
Greece = country_df.loc[["Greece"]].sort_values(by='Greece', axis=1, ascending=False)
Greece = Greece.iloc[:, : 20]
Greece

,Population thousands,All Causes,Ischaemic heart disease,"Trachea, bronchus, lung cancers",Chronic obstructive pulmonary disease,Ischaemic stroke,Haemorrhagic stroke,Depressive disorders,Alzheimer disease and other dementias,Major depressive disorder,Diabetes mellitus,Colon and rectum cancers,Migraine,Anxiety disorders,Breast cancer,Pancreas cancer,Brain and nervous system cancers,Edentulism,Stomach cancer,Osteoarthritis
Greece,11184.0,3273.038198,373.901907,167.67541,120.427489,119.817539,108.630405,85.859433,69.024986,66.691459,63.553216,58.861025,56.829878,56.11499,54.58469,38.295989,34.471233,34.352671,32.137082,31.212442

In [90]:
#India
India = country_df.loc[["India"]].sort_values(by='India', axis=1, ascending=False)
India = India.iloc[:, : 20]
India

,Population thousands,All Causes,Ischaemic heart disease,Preterm birth complications,Chronic obstructive pulmonary disease,Nutritional deficiencies,Diarrhoeal diseases,Iron-deficiency anaemia,Diabetes mellitus,Haemorrhagic stroke,Ischaemic stroke,Depressive disorders,Migraine,Cirrhosis due to hepatitis B,Major depressive disorder,Asthma,Congenital heart anomalies,Anxiety disorders,Skin diseases,Rheumatic heart disease
India,1324171.0,509005.725,44282.756687,31005.755796,22927.959119,22621.557953,19732.522547,16271.593207,11500.785772,9883.12247,8917.832285,7647.086055,6232.884329,6093.996463,6033.551059,5504.450195,4275.58239,4081.880412,3756.504378,3746.70137

In [91]:
#Indonesia
Indonesia = country_df.loc[["Indonesia"]].sort_values(by='Indonesia', axis=1, ascending=False)
Indonesia = Indonesia.iloc[:, : 20]
Indonesia

,Population thousands,All Causes,Ischaemic heart disease,Haemorrhagic stroke,Diabetes mellitus,Preterm birth complications,Diarrhoeal diseases,Chronic obstructive pulmonary disease,Ischaemic stroke,Asthma,Nutritional deficiencies,Iron-deficiency anaemia,Alzheimer disease and other dementias,Depressive disorders,Skin diseases,"Trachea, bronchus, lung cancers",Hypertensive heart disease,Migraine,Anxiety disorders,Chronic kidney disease due to diabetes
Indonesia,261115.0,87574.365188,8487.848569,4779.366857,4033.045144,2574.50271,2295.870563,2000.106363,1998.229134,1680.670286,1650.987745,1071.742951,1045.337914,983.555037,947.452089,940.143704,910.934252,878.59402,856.854739,840.834556

In [92]:
#Ireland
Ireland = country_df.loc[["Ireland"]].sort_values(by='Ireland', axis=1, ascending=False)
Ireland = Ireland.iloc[:, : 20]
Ireland

,Population thousands,All Causes,Ischaemic heart disease,"Trachea, bronchus, lung cancers",Chronic obstructive pulmonary disease,Alzheimer disease and other dementias,Depressive disorders,Major depressive disorder,Migraine,Anxiety disorders,Diabetes mellitus,Colon and rectum cancers,Breast cancer,Asthma,Ischaemic stroke,Haemorrhagic stroke,Alcohol use disorders,Skin diseases,Opioid use disorders,Edentulism
Ireland,4726.0,1070.38531,85.725415,41.684412,35.934094,35.414323,33.395762,25.944533,24.474758,24.458824,23.728167,22.920431,21.155839,18.303144,17.774661,16.831563,13.790877,12.755075,12.648922,12.546995

In [93]:
#Italy
Italy = country_df.loc[["Italy"]].sort_values(by='Italy', axis=1, ascending=False)
Italy = Italy.iloc[:, : 20]
Italy

,Population thousands,All Causes,Ischaemic heart disease,"Trachea, bronchus, lung cancers",Alzheimer disease and other dementias,Diabetes mellitus,Chronic obstructive pulmonary disease,Ischaemic stroke,Haemorrhagic stroke,Depressive disorders,Colon and rectum cancers,Migraine,Breast cancer,Anxiety disorders,Major depressive disorder,Hypertensive heart disease,Pancreas cancer,Stomach cancer,Liver cancer,Osteoarthritis
Italy,59430.0,17125.66568,1537.538067,698.588108,666.743901,579.102149,452.232585,442.253391,418.501717,410.420827,396.752525,345.376,317.549798,316.509992,310.354053,228.696804,223.835288,202.813075,197.507723,173.610106

In [94]:
#Japan
Japan = country_df.loc[["Japan"]].sort_values(by='Japan', axis=1, ascending=False)
Japan = Japan.iloc[:, : 20]
Japan

,Population thousands,All Causes,Ischaemic heart disease,"Trachea, bronchus, lung cancers",Ischaemic stroke,Alzheimer disease and other dementias,Chronic obstructive pulmonary disease,Colon and rectum cancers,Diabetes mellitus,Haemorrhagic stroke,Stomach cancer,Depressive disorders,Major depressive disorder,Pancreas cancer,Liver cancer,Migraine,Anxiety disorders,Edentulism,Chronic kidney disease due to diabetes,Breast cancer
Japan,127749.0,35619.331059,2315.051,1389.004544,1234.380297,1126.773893,1068.790269,1015.668498,1004.445687,963.649039,950.289384,808.800246,657.326576,614.418695,559.836874,486.824052,415.865717,399.484036,391.363236,384.167245

In [95]:
#Mexico
Mexico = country_df.loc[["Mexico"]].sort_values(by='Mexico', axis=1, ascending=False)
Mexico = Mexico.iloc[:, : 20]
Mexico

,Population thousands,All Causes,Diabetes mellitus,Ischaemic heart disease,Preterm birth complications,Depressive disorders,Migraine,Chronic obstructive pulmonary disease,Haemorrhagic stroke,Nutritional deficiencies,Congenital heart anomalies,Major depressive disorder,Alcohol use disorders,Skin diseases,Anxiety disorders,Cirrhosis due to alcohol use,Epilepsy,Ischaemic stroke,Osteoarthritis,Cirrhosis due to hepatitis C
Mexico,127540.0,31199.489906,3507.629066,2074.962176,713.022176,606.051403,536.244586,523.402553,493.189274,487.394501,487.174371,484.327782,396.771078,391.296531,366.859752,334.583535,306.769468,298.126568,257.202025,253.812185

In [96]:
#Philippines
Philippines = country_df.loc[["Philippines"]].sort_values(by='Philippines', axis=1, ascending=False)
Philippines = Philippines.iloc[:, : 20]
Philippines

,Population thousands,All Causes,Ischaemic heart disease,Haemorrhagic stroke,Diabetes mellitus,Preterm birth complications,Chronic obstructive pulmonary disease,Asthma,Diarrhoeal diseases,Ischaemic stroke,Nutritional deficiencies,Congenital heart anomalies,Chronic kidney disease due to diabetes,Skin diseases,Hypertensive heart disease,Depressive disorders,Breast cancer,Migraine,Anxiety disorders,"Trachea, bronchus, lung cancers"
Philippines,103320.0,33904.976344,3374.754556,1955.113522,1200.171601,1127.774078,861.155083,695.288042,680.78726,554.654311,541.672817,476.696372,443.678553,438.014289,392.25918,383.470785,328.233206,325.601366,325.508677,321.92976

In [97]:
#Thailand
Thailand = country_df.loc[["Thailand"]].sort_values(by='Thailand', axis=1, ascending=False)
Thailand = Thailand.iloc[:, : 20]
Thailand

,Population thousands,All Causes,Ischaemic heart disease,Haemorrhagic stroke,Diabetes mellitus,Chronic obstructive pulmonary disease,Liver cancer,Alzheimer disease and other dementias,"Trachea, bronchus, lung cancers",Chronic kidney disease due to diabetes,Depressive disorders,Ischaemic stroke,Liver cancer secondary to hepatitis B,Skin diseases,Preterm birth complications,Asthma,Migraine,Major depressive disorder,Anxiety disorders,Cirrhosis due to hepatitis B
Thailand,68864.0,22137.704125,1321.498835,814.081239,789.061113,773.556792,674.481855,632.24363,528.034045,444.196024,383.42673,370.121191,335.119325,323.829316,283.621127,258.95902,254.141957,251.397514,249.346168,235.670138

In [98]:
#Viet Nam
Viet_Nam = country_df.loc[["Viet Nam"]].sort_values(by='Viet Nam', axis=1, ascending=False)
Viet_Nam = Viet_Nam.iloc[:, : 20]
Viet_Nam

,Population thousands,All Causes,Ischaemic heart disease,Haemorrhagic stroke,Liver cancer,Preterm birth complications,Diabetes mellitus,Chronic obstructive pulmonary disease,Ischaemic stroke,"Trachea, bronchus, lung cancers",Alzheimer disease and other dementias,Congenital heart anomalies,Depressive disorders,Liver cancer secondary to hepatitis B,Stomach cancer,Migraine,Liver cancer secondary to alcohol use,Skin diseases,Asthma,Diarrhoeal diseases
Viet Nam,94569.0,25192.804109,1310.044142,1278.916777,945.8851,834.190955,736.4493,677.673431,644.196545,593.818776,504.198614,472.72132,433.70218,421.147357,368.283732,333.866217,324.828164,324.340962,324.011084,313.053989

In [99]:
#Russia
Russia = country_df.loc[["Russian Federation"]].sort_values(by='Russian Federation', axis=1, ascending=False)
Russia = Russia.iloc[:, : 20]
Russia

,Population thousands,All Causes,Ischaemic heart disease,Ischaemic stroke,Alcohol use disorders,"Cardiomyopathy, myocarditis, endocarditis",Haemorrhagic stroke,"Trachea, bronchus, lung cancers",Colon and rectum cancers,Depressive disorders,Opioid use disorders,Stomach cancer,Breast cancer,Alzheimer disease and other dementias,Major depressive disorder,Diabetes mellitus,Migraine,Chronic obstructive pulmonary disease,Cirrhosis due to hepatitis B,Osteoarthritis
Russian Federation,143965.0,64873.714094,11111.42047,4410.773014,2060.365566,1969.615125,1815.61881,1678.847647,1140.206738,1072.708654,1037.558982,1024.450448,830.939828,818.699202,815.947192,769.546517,726.886969,717.720794,621.949051,558.08436

In [100]:
#South Korea
South_Korea = country_df.loc[["Republic of Korea"]].sort_values(by='Republic of Korea', axis=1, ascending=False)
South_Korea = South_Korea.iloc[:, : 20]
South_Korea

,Population thousands,All Causes,Diabetes mellitus,Ischaemic heart disease,"Trachea, bronchus, lung cancers",Depressive disorders,Ischaemic stroke,Liver cancer,Major depressive disorder,Haemorrhagic stroke,Alzheimer disease and other dementias,Chronic obstructive pulmonary disease,Stomach cancer,Migraine,Liver cancer secondary to hepatitis B,Colon and rectum cancers,Anxiety disorders,Alcohol use disorders,Asthma,Skin diseases
Republic of Korea,50792.0,11312.673324,512.283235,492.953599,407.103899,379.924579,343.521827,327.551915,322.346566,276.997917,272.677699,272.023409,239.635116,230.421816,219.956735,213.901195,197.404469,166.18464,137.168664,134.885368

In [101]:
#UK
United_Kingdom = country_df.loc[["United Kingdom"]].sort_values(by='United Kingdom', axis=1, ascending=False)
United_Kingdom = United_Kingdom.iloc[:, : 20]
United_Kingdom

,Population thousands,All Causes,Ischaemic heart disease,Alzheimer disease and other dementias,"Trachea, bronchus, lung cancers",Chronic obstructive pulmonary disease,Depressive disorders,Major depressive disorder,Colon and rectum cancers,Ischaemic stroke,Haemorrhagic stroke,Migraine,Diabetes mellitus,Breast cancer,Anxiety disorders,Asthma,Skin diseases,Prostate cancer,Opioid use disorders,Oesophagus cancer
United Kingdom,65789.0,17925.027078,1335.34633,997.214261,741.426064,680.107245,481.363761,373.846726,363.828503,355.201009,329.711562,320.829813,312.419554,311.613912,296.78543,251.479227,211.58861,205.507977,197.341686,182.855703

In [102]:
frames = [Caribbean, China, France, Greece, India, Indonesia, Ireland, Italy, Japan, Mexico, Philippines, Thailand, Viet_Nam, Russia, South_Korea, United_Kingdom]
combined_countries = pd.concat(frames, sort=True)
combined_countries
# note that NaN does not mean that the country does not have any instances of a particular disease, 
# but that the disease in question is not 
# in the top N diseases, in this case, top 20. 
# I will use this dataframe to attempt to cluster countries together based on similar diseases. 
# I may instead choose to take all diseases together to compare similarities across all diseases
# depending on how useful the results appear to be

,Alcohol use disorders,All Causes,Alzheimer disease and other dementias,Anxiety disorders,Asthma,Brain and nervous system cancers,Breast cancer,"Cardiomyopathy, myocarditis, endocarditis",Chronic kidney disease due to diabetes,Chronic obstructive pulmonary disease,...,Osteoarthritis,Pancreas cancer,Population thousands,Preterm birth complications,Prostate cancer,Rheumatic heart disease,Schizophrenia,Skin diseases,Stomach cancer,"Trachea, bronchus, lung cancers"
Caribbean,NaN,13905.819584,156.013413,152.777611,198.905045,NaN,NaN,NaN,NaN,193.084670,...,NaN,NaN,38390.0,477.236529,NaN,NaN,NaN,NaN,NaN,195.919851
China,NaN,376370.900000,10041.762203,4275.024730,NaN,NaN,NaN,NaN,NaN,17937.916706,...,4323.652582,NaN,1411415.0,NaN,NaN,NaN,4561.340778,NaN,7759.098337,14705.861537
France,223.113543,16782.841238,677.400662,351.145909,193.112460,NaN,330.333607,NaN,NaN,287.340769,...,NaN,225.665361,64721.0,NaN,NaN,NaN,NaN,189.569308,NaN,827.288245
Greece,NaN,3273.038198,69.024986,56.114990,NaN,34.471233,54.584690,NaN,NaN,120.427489,...,31.212442,38.295989,11184.0,NaN,NaN,NaN,NaN,NaN,32.137082,167.675410
India,NaN,509005.725000,NaN,4081.880412,5504.450195,NaN,NaN,NaN,NaN,22927.959119,...,NaN,NaN,1324171.0,31005.755796,NaN,3746.70137,NaN,3756.504378,NaN,NaN
Indonesia,NaN,87574.365188,1045.337914,856.854739,1680.670286,NaN,NaN,NaN,840.834556,2000.106363,...,NaN,NaN,261115.0,2574.502710,NaN,NaN,NaN,947.452089,NaN,940.143704
Ireland,13.790877,1070.385310,35.414323,24.458824,18.303144,NaN,21.155839,NaN,NaN,35.934094,...,NaN,NaN,4726.0,NaN,NaN,NaN,NaN,12.755075,NaN,41.684412
Italy,NaN,17125.665680,666.743901,316.509992,NaN,NaN,317.549798,NaN,NaN,452.232585,...,173.610106,223.835288,59430.0,NaN,NaN,NaN,NaN,NaN,202.813075,698.588108
Japan,NaN,35619.331059,1126.773893,415.865717,NaN,NaN,384.167245,NaN,391.363236,1068.790269,...,NaN,614.418695,127749.0,NaN,NaN,NaN,NaN,NaN,950.289384,1389.004544
Mexico,396.771078,31199.489906,NaN,366.859752,NaN,NaN,NaN,NaN,NaN,523.402553,...,257.202025,NaN,127540.0,713.022176,NaN,NaN,NaN,391.296531,NaN,NaN
Philippines,NaN,33904.976344,NaN,325.508677,695.288042,NaN,328.233206,NaN,443.678553,861.155083,...,NaN,NaN,103320.0,1127.774078,NaN,NaN,NaN,438.014289,NaN,321.929760
Thailand,NaN,22137.704125,632.243630,249.346168,258.959020,NaN,NaN,NaN,444.196024,773.556792,...,NaN,NaN,68864.0,283.621127,NaN,NaN,NaN,323.829316,NaN,528.034045
Viet Nam,NaN,25192.804109,504.198614,NaN,324.011084,NaN,NaN,NaN,NaN,677.673431,...,NaN,NaN,94569.0,834.190955,NaN,NaN,NaN,324.340962,368.283732,593.818776
Russian Federation,2060.365566,64873.714094,818.699202,NaN,NaN,NaN,830.939828,1969.615125,NaN,717.720794,...,558.084360,NaN,143965.0,NaN,NaN,NaN,NaN,NaN,1024.450448,1678.847647
Republic of Korea,166.184640,11312.673324,272.677699,197.404469,137.168664,NaN,NaN,NaN,NaN,272.023409,...,NaN,NaN,50792.0,NaN,NaN,NaN,NaN,134.885368,239.635116,407.103899
United Kingdom,NaN,17925.027078,997.214261,296.785430,251.479227,NaN,311.613912,NaN,NaN,680.107245,...,NaN,NaN,65789.0,NaN,205.507977,NaN,NaN,211.588610,NaN,741.426064

In [21]:
combined_countries.to_csv('granular_disease.csv')