*Cleaned .xls file manually to remove columns/rows not able to be parsed by pandas.*
*Also removed ailments clearly not caused by food like injuries, exposure to mechanical forces, natural disasters, other unintentional injuries, intentional injuries, self-harm, interpersonal violence, collective violence and legal intervention, drowning, falls, road injury, unintentional injuries, injuries, rabies, yellow fever, dengue and other vector diseases, SIDS, 
.*

In [16]:
import pandas as pd
import numpy as np

disease_df = pd.read_excel("cleanedGHE2016_DALYs-2016-country.xlsx", encoding='latin-1')
columns = disease_df.iloc[:,0].tolist()
disease_df.tail()

,GHE cause,Afghanistan,Albania,Algeria,Angola,Antigua and Barbuda,Argentina,Armenia,Australia,Austria,...,United Republic of Tanzania,United States of America,Uruguay,Uzbekistan,Vanuatu,Venezuela (Bolivarian Republic of),Viet Nam,Yemen,Zambia,Zimbabwe
164,Periodontal disease,13.291041,1.901364,26.689878,8.999782,0.101141,30.035238,1.901050,14.402867,9.295235,...,3.707525,142.809625,3.527374,13.416079,0.018951,23.685969,36.286257,11.120515,6.605976,1.594521
165,Edentulism,18.639215,6.205911,45.717420,13.403549,0.135974,58.413680,7.741004,64.388641,28.655879,...,14.810599,662.273879,5.601263,43.201856,0.117696,43.919465,48.381986,16.993919,4.523364,12.853295
166,Other oral disorders,14.397070,1.628111,20.575783,10.670629,0.050553,23.706889,1.735528,14.019176,5.143684,...,23.539132,183.614166,1.926957,15.681243,0.128372,16.504001,51.714718,12.221351,7.061288,7.056891
167,Poisonings,30.874814,0.817360,23.142287,59.014681,0.022178,15.040495,1.120259,4.354529,1.524359,...,115.454541,160.453618,0.752162,21.427973,0.142984,6.067724,42.517815,80.585481,38.797548,27.350160
168,"Fire, heat and hot substances",39.341402,1.799365,49.888284,85.099931,0.094914,32.844381,3.719641,11.247204,4.811335,...,204.854289,246.946217,3.108423,49.046151,0.218128,19.503225,40.997041,94.510809,56.926053,44.232524

In [17]:

del disease_df['GHE cause']
country_df = disease_df.transpose()
country_df.columns = columns
#country_df.sort_values('')
country_df.head(10)

,Population thousands,Tuberculosis,Diarrhoeal diseases,Childhood-cluster diseases,Whooping cough,Diphtheria,Measles,Tetanus,Meningitis,Encephalitis,...,Congenital heart anomalies,Other chromosomal anomalies,Other congenital anomalies,Oral conditions,Dental caries,Periodontal disease,Edentulism,Other oral disorders,Poisonings,"Fire, heat and hot substances"
Afghanistan,34656.0,504.617537,709.743629,207.211107,19.144073,1.861497,6.812915e+01,1.180764e+02,255.044253,19.827516,...,237.038007,30.388383,291.526373,55.242597,8.915272,13.291041,18.639215,14.397070,30.874814,39.341402
Albania,2926.0,0.274134,2.201231,0.211117,0.004362,0.001972,3.526984e-03,2.012567e-01,1.540692,1.631294,...,9.831769,0.964302,5.501639,10.521400,0.786014,1.901364,6.205911,1.628111,0.817360,1.799365
Algeria,40606.0,97.657964,154.800703,10.184277,0.213864,0.079935,5.902308e+00,3.988170e+00,32.291928,19.152116,...,157.288703,40.564972,233.093213,102.517477,9.534396,26.689878,45.717420,20.575783,23.142287,49.888284
Angola,28813.0,848.825382,1526.057294,91.822942,4.803701,0.551929,4.450591e+01,4.196140e+01,287.128432,19.321514,...,211.273574,23.802830,342.563978,37.524285,4.450325,8.999782,13.403549,10.670629,59.014681,85.099931
Antigua and Barbuda,101.0,0.003767,0.142901,0.000032,0.000025,0.000006,3.805812e-10,9.526739e-07,0.030887,0.119274,...,0.414945,0.037037,0.253062,0.320139,0.032470,0.101141,0.135974,0.050553,0.022178,0.094914
Argentina,43847.0,24.097570,36.303180,2.215514,2.062994,0.006661,3.288331e-06,1.458554e-01,18.346852,70.218030,...,107.346439,25.125515,127.355314,128.981758,16.825951,30.035238,58.413680,23.706889,15.040495,32.844381
Armenia,2925.0,2.475986,3.147583,0.293145,0.010081,0.002211,2.792270e-01,1.625337e-03,1.329271,1.097469,...,6.757167,0.549264,9.680448,12.177219,0.799637,1.901050,7.741004,1.735528,1.120259,3.719641
Australia,24126.0,1.242870,7.101818,0.206300,0.185532,0.005093,1.272957e-02,2.945258e-03,2.176410,6.479078,...,17.269149,11.822813,28.116768,97.360689,4.550005,14.402867,64.388641,14.019176,4.354529,11.247204
Austria,8712.0,1.539760,4.740230,0.122808,0.121289,0.000729,7.869015e-04,3.957289e-06,1.042314,2.980158,...,5.903626,4.942758,13.397488,46.445593,3.350795,9.295235,28.655879,5.143684,1.524359,4.811335
Azerbaijan,9725.0,29.899556,38.961588,1.305627,0.232289,0.024484,3.257430e-04,1.048527e+00,6.334107,4.238014,...,52.744917,2.411711,24.863049,31.685778,2.528109,5.410238,18.370797,5.376634,3.910363,24.144654

*Check one country*

In [18]:
United_States = country_df.loc[["United States of America"], :]
United_States.dropna()

United_States.sort_values(by='United States of America', axis=1, ascending=False)

,Population thousands,Cardiovascular diseases,Malignant neoplasms,Ischaemic heart disease,Musculoskeletal diseases,Respiratory diseases,Chronic obstructive pulmonary disease,Drug use disorders,Diabetes mellitus,Alzheimer disease and other dementias,...,Diphtheria,Tetanus,Leprosy,Measles,Intestinal nematode infections,Ascariasis,Trichuriasis,Hookworm disease,Food-bourne trematodes,Vitamin A deficiency
United States of America,322180.0,17309.515201,14916.517554,9269.600899,6880.965475,6220.931219,4519.202379,4110.199695,4054.681575,3617.091421,...,0.065551,0.034951,0.00273,0.001687,NaN,NaN,NaN,NaN,NaN,NaN

*Find top N diseases for each country*


First I separated out the selected countries for which we have sufficient recipes, and then sorted them to get the top diseases. The first column is just the population data, which is necessary to include as it allows calculation of percent of population with each disease. For our purposes, it appears that the top 10 diseases allows for enough variety while not being overwhelming. But that number may change after further exploration or pattern mining.

In [22]:
#China
China = country_df.loc[["China"]].sort_values(by='China', axis=1, ascending=False)

China.drop([])

,Population thousands,Cardiovascular diseases,Malignant neoplasms,Stroke,Ischaemic heart disease,Haemorrhagic stroke,Respiratory diseases,Ischaemic stroke,Sense organ diseases,Musculoskeletal diseases,...,Leprosy,Vitamin A deficiency,Acute hepatitis A,Acute hepatitis E,Tetanus,Trichuriasis,Sickle cell disorders and trait,Acute hepatitis C,Whooping cough,Diphtheria
China,1411415.0,97208.17283,61112.833179,47588.808765,37324.428987,27271.836983,20826.413469,20316.971024,19904.681177,19790.679427,...,34.78702,25.269238,19.686378,19.603868,18.812434,12.112664,8.759536,4.36898,1.520556,0.62853

In [37]:
#France
France = country_df.loc[["France"]].sort_values(by='France', axis=1, ascending=False)
France

,Population thousands,Malignant neoplasms,Cardiovascular diseases,Musculoskeletal diseases,Ischaemic heart disease,Sense organ diseases,"Trachea, bronchus, lung cancers",Other circulatory diseases,Back and neck pain,Alzheimer disease and other dementias,...,Tetanus,Diphtheria,Acute hepatitis C,Intestinal nematode infections,Ascariasis,Trichuriasis,Hookworm disease,Food-bourne trematodes,Leprosy,Vitamin A deficiency
France,64721.0,3698.337421,2432.586459,1226.51543,927.52799,856.726437,827.288245,704.218937,691.575884,677.400662,...,0.023693,0.020739,0.007982,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
#Greece
Greece = country_df.loc[["Greece"]].sort_values(by='Greece', axis=1, ascending=False)
Greece

,Population thousands,Cardiovascular diseases,Malignant neoplasms,Ischaemic heart disease,Stroke,Musculoskeletal diseases,Respiratory diseases,"Trachea, bronchus, lung cancers",Sense organ diseases,Back and neck pain,...,Measles,Acute hepatitis C,Diphtheria,Leprosy,Intestinal nematode infections,Ascariasis,Trichuriasis,Hookworm disease,Food-bourne trematodes,Vitamin A deficiency
Greece,11184.0,750.563032,645.676802,373.901907,228.447943,217.345817,192.712561,167.67541,160.928803,132.193606,...,0.0137,0.004715,0.00025,0.000002,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
#India
India = country_df.loc[["India"]].sort_values(by='India', axis=1, ascending=False)
India

,Population thousands,Cardiovascular diseases,Ischaemic heart disease,Preterm birth complications,Respiratory diseases,Malignant neoplasms,Lower respiratory infections,Chronic obstructive pulmonary disease,Sense organ diseases,Digestive diseases,...,Attention deficit/hyperactivity syndrome,Malignant skin melanoma,Cleft lip and cleft palate,Acute glomerulonephritis,Acute hepatitis C,Amphetamine use disorders,Trichuriasis,Mesothelioma,Diphtheria,Food-bourne trematodes
India,1324171.0,72208.856423,44282.756687,31005.755796,29698.299656,27909.261419,23742.307356,22927.959119,20521.275535,19944.092246,...,58.226222,52.915571,47.133395,42.298621,35.78712,30.556722,29.358873,17.668985,3.922998,NaN

In [40]:
#Indonesia
Indonesia = country_df.loc[["Indonesia"]].sort_values(by='Indonesia', axis=1, ascending=False)
Indonesia

,Population thousands,Cardiovascular diseases,Ischaemic heart disease,Stroke,Malignant neoplasms,Haemorrhagic stroke,Digestive diseases,Diabetes mellitus,Tuberculosis,Respiratory diseases,...,Trichuriasis,Cocaine use disorders,Vitamin A deficiency,Acute hepatitis C,Mesothelioma,Cleft lip and cleft palate,Sickle cell disorders and trait,Diphtheria,Acute glomerulonephritis,Food-bourne trematodes
Indonesia,261115.0,17962.079622,8487.848569,6777.595875,6729.544821,4779.366857,4465.707557,4033.045144,3954.780654,3852.327043,...,9.246829,7.179485,7.110394,4.696646,4.268868,4.101145,3.398187,2.692362,2.545504,NaN

In [41]:
#Ireland
Ireland = country_df.loc[["Ireland"]].sort_values(by='Ireland', axis=1, ascending=False)
Ireland

,Population thousands,Malignant neoplasms,Cardiovascular diseases,Ischaemic heart disease,Musculoskeletal diseases,Respiratory diseases,Sense organ diseases,Back and neck pain,"Trachea, bronchus, lung cancers",Chronic obstructive pulmonary disease,...,Diphtheria,Measles,Tetanus,Intestinal nematode infections,Ascariasis,Trichuriasis,Hookworm disease,Food-bourne trematodes,Leprosy,Vitamin A deficiency
Ireland,4726.0,203.962573,162.901155,85.725415,81.344252,64.385373,48.375572,46.32303,41.684412,35.934094,...,0.000298,0.00001,0.000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
#Italy
Italy = country_df.loc[["Italy"]].sort_values(by='Italy', axis=1, ascending=False)
Italy

,Population thousands,Malignant neoplasms,Cardiovascular diseases,Ischaemic heart disease,Musculoskeletal diseases,Sense organ diseases,Stroke,Back and neck pain,Respiratory diseases,"Trachea, bronchus, lung cancers",...,Measles,Acute hepatitis C,Diphtheria,Leprosy,Intestinal nematode infections,Ascariasis,Trichuriasis,Hookworm disease,Food-bourne trematodes,Vitamin A deficiency
Italy,59430.0,3500.084047,3352.052446,1537.538067,1278.439174,1023.033677,860.755109,741.693047,712.721547,698.588108,...,0.032563,0.029019,0.001477,0.000946,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
#Japan
Japan = country_df.loc[["Japan"]].sort_values(by='Japan', axis=1, ascending=False)
Japan

,Population thousands,Malignant neoplasms,Cardiovascular diseases,Musculoskeletal diseases,Ischaemic heart disease,Sense organ diseases,Stroke,Respiratory diseases,Lower respiratory infections,Back and neck pain,...,Whooping cough,Tetanus,Measles,Acute hepatitis C,Diphtheria,Leprosy,Ascariasis,Trichuriasis,Hookworm disease,Vitamin A deficiency
Japan,127749.0,7330.368572,5997.114191,2832.897258,2315.051,2210.220419,2198.029351,1989.68735,1598.977217,1566.642211,...,0.112825,0.102348,0.054785,0.023116,0.006082,0.001863,NaN,NaN,NaN,NaN

In [44]:
#Mexico
Mexico = country_df.loc[["Mexico"]].sort_values(by='Mexico', axis=1, ascending=False)
Mexico

,Population thousands,Cardiovascular diseases,Diabetes mellitus,Malignant neoplasms,Ischaemic heart disease,Digestive diseases,Sense organ diseases,Musculoskeletal diseases,Congenital anomalies,Respiratory diseases,...,Acute hepatitis A,Nasopharynx,Acute glomerulonephritis,Tetanus,Hookworm disease,Diphtheria,Acute hepatitis C,Leprosy,Measles,Food-bourne trematodes
Mexico,127540.0,3539.820695,3507.629066,2392.126638,2074.962176,2026.196165,1573.073844,1519.119862,1165.624468,950.571876,...,3.454574,3.199603,1.461602,0.238777,0.172956,0.094301,0.074319,0.045188,6.414760e-07,NaN

In [45]:
#Philippines
Philippines = country_df.loc[["Philippines"]].sort_values(by='Philippines', axis=1, ascending=False)
Philippines

,Population thousands,Cardiovascular diseases,Ischaemic heart disease,Lower respiratory infections,Stroke,Malignant neoplasms,Haemorrhagic stroke,Respiratory diseases,Sense organ diseases,Diabetes mellitus,...,Cocaine use disorders,Vitamin A deficiency,Multiple sclerosis,Whooping cough,Food-bourne trematodes,Diphtheria,Sickle cell disorders and trait,Mesothelioma,Leprosy,Acute hepatitis C
Philippines,103320.0,6872.714605,3374.754556,2659.781893,2509.767846,2251.310523,1955.113522,1724.919861,1361.715954,1200.171601,...,2.796294,2.272066,2.186763,1.883762,1.692957,1.666749,1.356243,0.420603,0.345408,0.06931

In [46]:
#Thailand
Thailand = country_df.loc[["Thailand"]].sort_values(by='Thailand', axis=1, ascending=False)
Thailand

,Population thousands,Cardiovascular diseases,Malignant neoplasms,Ischaemic heart disease,Musculoskeletal diseases,Stroke,Sense organ diseases,Respiratory diseases,Lower respiratory infections,Digestive diseases,...,Mesothelioma,Measles,Vitamin A deficiency,Acute glomerulonephritis,Acute hepatitis C,Cleft lip and cleft palate,Acute hepatitis A,Sickle cell disorders and trait,Trichuriasis,Diphtheria
Thailand,68864.0,3031.552103,2871.926384,1321.498835,1267.984004,1184.202454,1165.43649,1075.075545,959.8043,909.175738,...,0.855627,0.624811,0.577818,0.521563,0.4588,0.456194,0.374189,0.227413,0.095528,0.062979

In [47]:
#Viet Nam
Viet_Nam = country_df.loc[["Viet Nam"]].sort_values(by='Viet Nam', axis=1, ascending=False)
Viet_Nam

,Population thousands,Cardiovascular diseases,Malignant neoplasms,Stroke,Sense organ diseases,Ischaemic heart disease,Haemorrhagic stroke,Musculoskeletal diseases,Respiratory diseases,Liver cancer,...,Urolithiasis,Acute hepatitis E,Cleft lip and cleft palate,Acute hepatitis A,Testicular cancer,Vitamin A deficiency,Acute glomerulonephritis,Sickle cell disorders and trait,Acute hepatitis C,Diphtheria
Viet Nam,94569.0,3854.18043,3275.560565,1923.113311,1381.182701,1310.044142,1278.916777,1208.310383,1050.21972,945.8851,...,2.419026,2.219784,1.690937,1.538863,1.326474,1.051543,0.720423,0.682266,0.642155,0.289924

In [48]:
#Russia
Russia = country_df.loc[["Russian Federation"]].sort_values(by='Russian Federation', axis=1, ascending=False)
Russia

,Population thousands,Cardiovascular diseases,Ischaemic heart disease,Malignant neoplasms,Stroke,Ischaemic stroke,Digestive diseases,Sense organ diseases,Musculoskeletal diseases,Alcohol use disorders,...,Acute hepatitis E,Acute hepatitis C,Diphtheria,Tetanus,Measles,Leprosy,Ascariasis,Trichuriasis,Hookworm disease,Vitamin A deficiency
Russian Federation,143965.0,20681.897233,11111.42047,9484.335748,6226.39186,4410.773014,2774.572698,2502.412724,2284.88357,2060.365566,...,0.656102,0.300165,0.213996,0.100466,0.083844,0.010103,NaN,NaN,NaN,NaN

In [49]:
#South Korea
South_Korea = country_df.loc[["Republic of Korea"]].sort_values(by='Republic of Korea', axis=1, ascending=False)
South_Korea

,Population thousands,Malignant neoplasms,Cardiovascular diseases,Musculoskeletal diseases,Stroke,Sense organ diseases,Diabetes mellitus,Ischaemic heart disease,Respiratory diseases,Back and neck pain,...,Childhood-cluster diseases,Tetanus,Leprosy,Whooping cough,Acute hepatitis C,Diphtheria,Measles,Trichuriasis,Ascariasis,Vitamin A deficiency
Republic of Korea,50792.0,2010.788772,1355.751857,929.587307,620.519748,598.238748,512.283235,492.953599,483.935778,468.319471,...,0.118587,0.084337,0.035596,0.032515,0.008335,0.001718,0.000017,0.000001,NaN,NaN

In [50]:
#UK
United_Kingdom = country_df.loc[["United Kingdom"]].sort_values(by='United Kingdom', axis=1, ascending=False)
United_Kingdom

,Population thousands,Malignant neoplasms,Cardiovascular diseases,Musculoskeletal diseases,Ischaemic heart disease,Respiratory diseases,Alzheimer disease and other dementias,Sense organ diseases,Back and neck pain,"Trachea, bronchus, lung cancers",...,Acute hepatitis C,Diphtheria,Tetanus,Ascariasis,Intestinal nematode infections,Leprosy,Trichuriasis,Hookworm disease,Food-bourne trematodes,Vitamin A deficiency
United Kingdom,65789.0,3452.840379,2827.101913,1395.752417,1335.34633,1106.791918,997.214261,872.817612,789.834964,741.426064,...,0.009892,0.008865,0.002782,0.001245,0.001245,0.000014,NaN,NaN,NaN,NaN